name = "Koti"
license = "MIT"
licenselink = "https://github.com/diwao/hestia-pure/blob/master/LICENSE.md"
description = ""
homepage = "http://diwao.com/hestia-pure/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "diwao"
  homepage = "http://diwao.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
