baseURL = "https://koti-koti.ru/"
languageCode = "en-us"
title = "KOTI-KOTI.RU"
theme = "koti-hestia-pure"
disqusShortname = "koti-koti-ru"
publishDir = "./../htdocs"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  copyright = "&copy;2018 Your name or company"
  github = "romanitalian"
  googleAnalytics = "UA-118341891-1"
  yandexMetrika = 25546679

  keywords="юмор, картинки, смешные коты, видео смешных котов, котоматрицы, картинки котов"
  description="Смешыне картинки котов и милота"
